version: 2.1
jobs:
  build:
    docker:
      - image: python:3.7-slim-buster

    steps:
      - checkout
      - run:
          name: install packages
          command: |
            apt-get update
            apt-get install -y git
      - run:
          name: pip install
          command: |
            pip install -r requirements.txt
            pip install -e .[test]
      - run:
          name: run test and coverage report
          command: |
            coverage run --source rogw/ -m unittest discover
            coveralls
